# English (United States) translations for Synse Server.
# Copyright (C) 2019 Vapor IO
# This file is distributed under the same license as the Synse Server
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
#
msgid ""
msgstr ""
"Project-Id-Version: Synse Server VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2019-07-24 13:49-0400\n"
"PO-Revision-Date: 2019-07-24 13:49-0400\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: en_US\n"
"Language-Team: en_US <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.7.0\n"

#: synse_server/cache.py:84
msgid "caching transaction"
msgstr ""

#: synse_server/cache.py:107
msgid "adding alias to cache"
msgstr ""

#: synse_server/cache.py:142
msgid "updating the device cache"
msgstr ""

#: synse_server/cache.py:152
msgid "no plugins found when updating device cache"
msgstr ""

#: synse_server/cache.py:159
msgid "getting devices from plugin"
msgstr ""

#: synse_server/cache.py:177
msgid "failed to get device(s)"
msgstr ""

#: synse_server/errors.py:52
msgid "an unexpected error occurred"
msgstr ""

#: synse_server/errors.py:76
msgid "invalid user input"
msgstr ""

#: synse_server/errors.py:88
msgid "resource not found"
msgstr ""

#: synse_server/errors.py:100
msgid "device action not supported"
msgstr ""

#: synse_server/errors.py:112
msgid "error processing the request"
msgstr ""

#: synse_server/plugin.py:95
msgid "plugin with id already registered"
msgstr ""

#: synse_server/plugin.py:98
msgid "registered plugin"
msgstr ""

#: synse_server/plugin.py:113
msgid "loading plugins from configuration"
msgstr ""

#: synse_server/plugin.py:120 synse_server/plugin.py:126
msgid "plugin from config"
msgstr ""

#: synse_server/plugin.py:146
msgid "failed plugin discovery via kubernetes"
msgstr ""

#: synse_server/plugin.py:163
msgid "refreshing plugin manager"
msgstr ""

#: synse_server/plugin.py:174
msgid "failed to register configured plugin"
msgstr ""

#: synse_server/plugin.py:188
msgid "failed to register discovered plugin"
msgstr ""

#: synse_server/plugin.py:193
msgid "plugin manager refresh complete"
msgstr ""

#: synse_server/plugin.py:261
msgid "marking plugin as active"
msgstr ""

#: synse_server/plugin.py:268
msgid "marking plugin as inactive"
msgstr ""

#: synse_server/server.py:83
msgid "initializing synse server"
msgstr ""

#: synse_server/server.py:88
msgid "loaded config"
msgstr ""

#: synse_server/server.py:95
msgid "configured logger"
msgstr ""

#: synse_server/server.py:104
msgid "running synse server"
msgstr ""

#: synse_server/server.py:118
msgid "application performance metrics enabled"
msgstr ""

#: synse_server/server.py:128
msgid "SSL configured for Synse Server"
msgstr ""

#: synse_server/server.py:133
msgid "starting Sanic application"
msgstr ""

#: synse_server/tasks.py:18
msgid "adding task"
msgstr ""

#: synse_server/tasks.py:28
msgid "rebuilding device cache"
msgstr ""

#: synse_server/cmd/scan.py:39 synse_server/tasks.py:36
msgid "failed to rebuild device cache"
msgstr ""

#: synse_server/api/http.py:26
msgid "processing request"
msgstr ""

#: synse_server/api/websocket.py:40
msgid "failed to load payload"
msgstr ""

#: synse_server/api/websocket.py:71
msgid "processing websocket request"
msgstr ""

#: synse_server/api/websocket.py:81
msgid "websocket request cancelled"
msgstr ""

#: synse_server/api/websocket.py:83
msgid "error processing request"
msgstr ""

#: synse_server/api/websocket.py:240
msgid "websocket raised ConnectionClosed - terminating read stream"
msgstr ""

#: synse_server/api/websocket.py:346
msgid "new websocket connection"
msgstr ""

#: synse_server/api/websocket.py:352
msgid "error loading websocket message"
msgstr ""

#: synse_server/api/websocket.py:356
msgid "got message"
msgstr ""

#: synse_server/api/websocket.py:360
msgid "error generating websocket response"
msgstr ""

#: synse_server/cmd/config.py:13 synse_server/cmd/info.py:18
#: synse_server/cmd/plugin.py:20 synse_server/cmd/plugin.py:60
#: synse_server/cmd/plugin.py:84 synse_server/cmd/read.py:61
#: synse_server/cmd/read.py:95 synse_server/cmd/read.py:132
#: synse_server/cmd/read.py:221 synse_server/cmd/scan.py:27
#: synse_server/cmd/tags.py:18 synse_server/cmd/test.py:13
#: synse_server/cmd/transaction.py:18 synse_server/cmd/transaction.py:59
#: synse_server/cmd/version.py:13 synse_server/cmd/write.py:20
#: synse_server/cmd/write.py:54
msgid "issuing command"
msgstr ""

#: synse_server/cmd/plugin.py:101
msgid "failed to get plugin health"
msgstr ""

#: synse_server/cmd/read.py:76
msgid "error while issuing gRPC request: read"
msgstr ""

#: synse_server/cmd/read.py:100 synse_server/cmd/write.py:25
#: synse_server/cmd/write.py:59
msgid "plugin not found for device {}"
msgstr ""

#: synse_server/cmd/read.py:109
msgid "error while issuing gRPC request: read device"
msgstr ""

#: synse_server/cmd/read.py:136
msgid "getting cached readings for plugin"
msgstr ""

#: synse_server/cmd/read.py:143
msgid "error while issuing gRPC request: read cache"
msgstr ""

#: synse_server/cmd/read.py:184
msgid "stream thread cancelled"
msgstr ""

#: synse_server/cmd/read.py:189
msgid "error while issuing gRPC request: read stream"
msgstr ""

#: synse_server/cmd/read.py:194
msgid "cancelling reading stream"
msgstr ""

#: synse_server/cmd/read.py:232
msgid "executing callback to cancel read stream threads"
msgstr ""

#: synse_server/cmd/read.py:244
msgid "collecting streamed readings..."
msgstr ""

#: synse_server/cmd/scan.py:35
msgid "forced scan: rebuilding device cache"
msgstr ""

#: synse_server/cmd/scan.py:51
msgid "failed to get devices from cache"
msgstr ""

#: synse_server/cmd/write.py:37
msgid "error while issuing gRPC request: async write"
msgstr ""

#: synse_server/cmd/write.py:73
msgid "error while issuing gRPC request: sync write"
msgstr ""

#: synse_server/discovery/kubernetes.py:34
msgid "Using namespace \"{}\" for k8s discovery"
msgstr ""

#: synse_server/discovery/kubernetes.py:76
msgid "No labels found for kubernetes service discovery via endpoints"
msgstr ""

#: synse_server/discovery/kubernetes.py:86
msgid "Using endpoint label selector: {}"
msgstr ""

#: synse_server/discovery/kubernetes.py:100
msgid "Found endpoint with name: {}"
msgstr ""

#: synse_server/discovery/kubernetes.py:108
msgid "No addresses for subset of endpoint - skipping ({})"
msgstr ""

#: synse_server/discovery/kubernetes.py:117
msgid "Address has no target_ref - skipping ({})"
msgstr ""

#: synse_server/discovery/kubernetes.py:122
msgid "Address is not a pod address - skipping ({})"
msgstr ""

#: synse_server/discovery/kubernetes.py:130
msgid "No ips found for endpoint, will not search for port"
msgstr ""

#: synse_server/discovery/kubernetes.py:137
msgid "No ports for subset of endpoint - skipping ({})"
msgstr ""

#: synse_server/discovery/kubernetes.py:147
msgid "skipping port (want name:http, but found name:{})"
msgstr ""

#: synse_server/discovery/kubernetes.py:159
msgid "found plugin: endpoint.name={}, ip={}, port={}"
msgstr ""

#: synse_server/discovery/kubernetes.py:166
msgid "Did not find any plugins via kubernetes endpoints (labels={})"
msgstr ""

